# Generated by Django 5.1 on 2024-09-03 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inmobiliaria', '0003_alter_comuna_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='arrendatario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='propiedades_arrendadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
